notifications:
    slack: designproject2018:rhfcpmTwX4UsvhNJ9jxyJ1P0

sudo: required

language: cpp

compiler:
  - gcc

before_script:
  - provision/install_opencv.sh
  - mkdir build && cd build
  - cmake ..

script: make